name: flutter_lid

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/flutter_lid/**"
      - ".github/workflows/flutter_lid.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/flutter_lid/**"
      - ".github/workflows/flutter_lid.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/flutter_lid
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1,4.0
      - name: Install Dependencies
        run: flutter packages get
      - name: Check format
        run: flutter format --set-exit-if-changed lib test example
      - name: Analyze
        run: flutter analyze lib test example
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.2
        with:
          path: packages/flutter_bloc/coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
